#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.ComponentModel.DataAnnotations;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cinema")]
	public partial class QuanLyRapPhimDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVE(VE instance);
    partial void UpdateVE(VE instance);
    partial void DeleteVE(VE instance);
    partial void InsertGhe(Ghe instance);
    partial void UpdateGhe(Ghe instance);
    partial void DeleteGhe(Ghe instance);
    partial void InsertKhach_Hang(Khach_Hang instance);
    partial void UpdateKhach_Hang(Khach_Hang instance);
    partial void DeleteKhach_Hang(Khach_Hang instance);
    partial void InsertLich_Chieu(Lich_Chieu instance);
    partial void UpdateLich_Chieu(Lich_Chieu instance);
    partial void DeleteLich_Chieu(Lich_Chieu instance);
    partial void InsertPhim(Phim instance);
    partial void UpdatePhim(Phim instance);
    partial void DeletePhim(Phim instance);
    partial void InsertPhong_Chieu(Phong_Chieu instance);
    partial void UpdatePhong_Chieu(Phong_Chieu instance);
    partial void DeletePhong_Chieu(Phong_Chieu instance);
    partial void InsertRap_phim(Rap_phim instance);
    partial void UpdateRap_phim(Rap_phim instance);
    partial void DeleteRap_phim(Rap_phim instance);
    partial void InsertThe_Loai(The_Loai instance);
    partial void UpdateThe_Loai(The_Loai instance);
    partial void DeleteThe_Loai(The_Loai instance);
    partial void InsertAccout(Accout instance);
    partial void UpdateAccout(Accout instance);
    partial void DeleteAccout(Accout instance);
    #endregion
		
		public QuanLyRapPhimDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CinemaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyRapPhimDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyRapPhimDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyRapPhimDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyRapPhimDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VE> VEs
		{
			get
			{
				return this.GetTable<VE>();
			}
		}
		
		public System.Data.Linq.Table<Ghe> Ghes
		{
			get
			{
				return this.GetTable<Ghe>();
			}
		}
		
		public System.Data.Linq.Table<Khach_Hang> Khach_Hangs
		{
			get
			{
				return this.GetTable<Khach_Hang>();
			}
		}
		
		public System.Data.Linq.Table<Lich_Chieu> Lich_Chieus
		{
			get
			{
				return this.GetTable<Lich_Chieu>();
			}
		}
		
		public System.Data.Linq.Table<Phim> Phims
		{
			get
			{
				return this.GetTable<Phim>();
			}
		}
		
		public System.Data.Linq.Table<Phong_Chieu> Phong_Chieus
		{
			get
			{
				return this.GetTable<Phong_Chieu>();
			}
		}
		
		public System.Data.Linq.Table<Rap_phim> Rap_phims
		{
			get
			{
				return this.GetTable<Rap_phim>();
			}
		}
		
		public System.Data.Linq.Table<The_Loai> The_Loais
		{
			get
			{
				return this.GetTable<The_Loai>();
			}
		}
		
		public System.Data.Linq.Table<Accout> Accouts
		{
			get
			{
				return this.GetTable<Accout>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VE")]
	public partial class VE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mave;
		
		private string _MaKH;
		
		private int _Maphim;
		
		private string _MaLC;
		
		private string _Maghe;
		
		private string _Maphong;
		
		private string _Tenphim;
		
		private System.DateTime _Thoigianchieu;
		
		private System.DateTime _Ngaychieu;
		
		private int _Phongso;
		
		private string _Gheso;
		
		private string _Thoiluong;
		
		private EntityRef<Ghe> _Ghe;
		
		private EntityRef<Khach_Hang> _Khach_Hang;
		
		private EntityRef<Lich_Chieu> _Lich_Chieu;
		
		private EntityRef<Phim> _Phim;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaveChanging(string value);
    partial void OnMaveChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaphimChanging(int value);
    partial void OnMaphimChanged();
    partial void OnMaLCChanging(string value);
    partial void OnMaLCChanged();
    partial void OnMagheChanging(string value);
    partial void OnMagheChanged();
    partial void OnMaphongChanging(string value);
    partial void OnMaphongChanged();
    partial void OnTenphimChanging(string value);
    partial void OnTenphimChanged();
    partial void OnThoigianchieuChanging(System.DateTime value);
    partial void OnThoigianchieuChanged();
    partial void OnNgaychieuChanging(System.DateTime value);
    partial void OnNgaychieuChanged();
    partial void OnPhongsoChanging(int value);
    partial void OnPhongsoChanged();
    partial void OnGhesoChanging(string value);
    partial void OnGhesoChanged();
    partial void OnThoiluongChanging(string value);
    partial void OnThoiluongChanged();
    #endregion
		
		public VE()
		{
			this._Ghe = default(EntityRef<Ghe>);
			this._Khach_Hang = default(EntityRef<Khach_Hang>);
			this._Lich_Chieu = default(EntityRef<Lich_Chieu>);
			this._Phim = default(EntityRef<Phim>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mave", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mave
		{
			get
			{
				return this._Mave;
			}
			set
			{
				if ((this._Mave != value))
				{
					this.OnMaveChanging(value);
					this.SendPropertyChanging();
					this._Mave = value;
					this.SendPropertyChanged("Mave");
					this.OnMaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._Khach_Hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphim", DbType="Int NOT NULL")]
		public int Maphim
		{
			get
			{
				return this._Maphim;
			}
			set
			{
				if ((this._Maphim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaphimChanging(value);
					this.SendPropertyChanging();
					this._Maphim = value;
					this.SendPropertyChanged("Maphim");
					this.OnMaphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLC", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaLC
		{
			get
			{
				return this._MaLC;
			}
			set
			{
				if ((this._MaLC != value))
				{
					if (this._Lich_Chieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLCChanging(value);
					this.SendPropertyChanging();
					this._MaLC = value;
					this.SendPropertyChanged("MaLC");
					this.OnMaLCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maghe", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Maghe
		{
			get
			{
				return this._Maghe;
			}
			set
			{
				if ((this._Maghe != value))
				{
					if (this._Ghe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMagheChanging(value);
					this.SendPropertyChanging();
					this._Maghe = value;
					this.SendPropertyChanged("Maghe");
					this.OnMagheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphong", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Maphong
		{
			get
			{
				return this._Maphong;
			}
			set
			{
				if ((this._Maphong != value))
				{
					this.OnMaphongChanging(value);
					this.SendPropertyChanging();
					this._Maphong = value;
					this.SendPropertyChanged("Maphong");
					this.OnMaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenphim", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tenphim
		{
			get
			{
				return this._Tenphim;
			}
			set
			{
				if ((this._Tenphim != value))
				{
					this.OnTenphimChanging(value);
					this.SendPropertyChanging();
					this._Tenphim = value;
					this.SendPropertyChanged("Tenphim");
					this.OnTenphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianchieu", DbType="DateTime NOT NULL")]
		public System.DateTime Thoigianchieu
		{
			get
			{
				return this._Thoigianchieu;
			}
			set
			{
				if ((this._Thoigianchieu != value))
				{
					this.OnThoigianchieuChanging(value);
					this.SendPropertyChanging();
					this._Thoigianchieu = value;
					this.SendPropertyChanged("Thoigianchieu");
					this.OnThoigianchieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaychieu", DbType="DateTime NOT NULL")]
		public System.DateTime Ngaychieu
		{
			get
			{
				return this._Ngaychieu;
			}
			set
			{
				if ((this._Ngaychieu != value))
				{
					this.OnNgaychieuChanging(value);
					this.SendPropertyChanging();
					this._Ngaychieu = value;
					this.SendPropertyChanged("Ngaychieu");
					this.OnNgaychieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phongso", DbType="Int NOT NULL")]
		public int Phongso
		{
			get
			{
				return this._Phongso;
			}
			set
			{
				if ((this._Phongso != value))
				{
					this.OnPhongsoChanging(value);
					this.SendPropertyChanging();
					this._Phongso = value;
					this.SendPropertyChanged("Phongso");
					this.OnPhongsoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gheso", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gheso
		{
			get
			{
				return this._Gheso;
			}
			set
			{
				if ((this._Gheso != value))
				{
					this.OnGhesoChanging(value);
					this.SendPropertyChanging();
					this._Gheso = value;
					this.SendPropertyChanged("Gheso");
					this.OnGhesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoiluong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Thoiluong
		{
			get
			{
				return this._Thoiluong;
			}
			set
			{
				if ((this._Thoiluong != value))
				{
					this.OnThoiluongChanging(value);
					this.SendPropertyChanging();
					this._Thoiluong = value;
					this.SendPropertyChanged("Thoiluong");
					this.OnThoiluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_VE", Storage="_Ghe", ThisKey="Maghe", OtherKey="Maghe", IsForeignKey=true)]
		public Ghe Ghe
		{
			get
			{
				return this._Ghe.Entity;
			}
			set
			{
				Ghe previousValue = this._Ghe.Entity;
				if (((previousValue != value) 
							|| (this._Ghe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ghe.Entity = null;
						previousValue.VEs.Remove(this);
					}
					this._Ghe.Entity = value;
					if ((value != null))
					{
						value.VEs.Add(this);
						this._Maghe = value.Maghe;
					}
					else
					{
						this._Maghe = default(string);
					}
					this.SendPropertyChanged("Ghe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_Hang_VE", Storage="_Khach_Hang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public Khach_Hang Khach_Hang
		{
			get
			{
				return this._Khach_Hang.Entity;
			}
			set
			{
				Khach_Hang previousValue = this._Khach_Hang.Entity;
				if (((previousValue != value) 
							|| (this._Khach_Hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khach_Hang.Entity = null;
						previousValue.VEs.Remove(this);
					}
					this._Khach_Hang.Entity = value;
					if ((value != null))
					{
						value.VEs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("Khach_Hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lich_Chieu_VE", Storage="_Lich_Chieu", ThisKey="MaLC", OtherKey="MaLC", IsForeignKey=true)]
		public Lich_Chieu Lich_Chieu
		{
			get
			{
				return this._Lich_Chieu.Entity;
			}
			set
			{
				Lich_Chieu previousValue = this._Lich_Chieu.Entity;
				if (((previousValue != value) 
							|| (this._Lich_Chieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lich_Chieu.Entity = null;
						previousValue.VEs.Remove(this);
					}
					this._Lich_Chieu.Entity = value;
					if ((value != null))
					{
						value.VEs.Add(this);
						this._MaLC = value.MaLC;
					}
					else
					{
						this._MaLC = default(string);
					}
					this.SendPropertyChanged("Lich_Chieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_VE", Storage="_Phim", ThisKey="Maphim", OtherKey="Maphim", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.VEs.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.VEs.Add(this);
						this._Maphim = value.Maphim;
					}
					else
					{
						this._Maphim = default(int);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ghe")]
	public partial class Ghe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Maghe;
		
		private string _Gheso;
		
		private string _Maphong;
		
		private EntitySet<VE> _VEs;
		
		private EntityRef<Phong_Chieu> _Phong_Chieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMagheChanging(string value);
    partial void OnMagheChanged();
    partial void OnGhesoChanging(string value);
    partial void OnGhesoChanged();
    partial void OnMaphongChanging(string value);
    partial void OnMaphongChanged();
    #endregion
		
		public Ghe()
		{
			this._VEs = new EntitySet<VE>(new Action<VE>(this.attach_VEs), new Action<VE>(this.detach_VEs));
			this._Phong_Chieu = default(EntityRef<Phong_Chieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maghe", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Maghe
		{
			get
			{
				return this._Maghe;
			}
			set
			{
				if ((this._Maghe != value))
				{
					this.OnMagheChanging(value);
					this.SendPropertyChanging();
					this._Maghe = value;
					this.SendPropertyChanged("Maghe");
					this.OnMagheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gheso", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gheso
		{
			get
			{
				return this._Gheso;
			}
			set
			{
				if ((this._Gheso != value))
				{
					this.OnGhesoChanging(value);
					this.SendPropertyChanging();
					this._Gheso = value;
					this.SendPropertyChanged("Gheso");
					this.OnGhesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphong", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Maphong
		{
			get
			{
				return this._Maphong;
			}
			set
			{
				if ((this._Maphong != value))
				{
					if (this._Phong_Chieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaphongChanging(value);
					this.SendPropertyChanging();
					this._Maphong = value;
					this.SendPropertyChanged("Maphong");
					this.OnMaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_VE", Storage="_VEs", ThisKey="Maghe", OtherKey="Maghe")]
		public EntitySet<VE> VEs
		{
			get
			{
				return this._VEs;
			}
			set
			{
				this._VEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_Chieu_Ghe", Storage="_Phong_Chieu", ThisKey="Maphong", OtherKey="Maphong", IsForeignKey=true)]
		public Phong_Chieu Phong_Chieu
		{
			get
			{
				return this._Phong_Chieu.Entity;
			}
			set
			{
				Phong_Chieu previousValue = this._Phong_Chieu.Entity;
				if (((previousValue != value) 
							|| (this._Phong_Chieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong_Chieu.Entity = null;
						previousValue.Ghes.Remove(this);
					}
					this._Phong_Chieu.Entity = value;
					if ((value != null))
					{
						value.Ghes.Add(this);
						this._Maphong = value.Maphong;
					}
					else
					{
						this._Maphong = default(string);
					}
					this.SendPropertyChanged("Phong_Chieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = this;
		}
		
		private void detach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Khach Hang]")]
	public partial class Khach_Hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _Hoten;
		
		private System.DateTime _Ngaysinh;
		
		private string _Diachi;
		
		private string _Email;
		
		private int _SDT;
		
		private int _CMND;
		
		private int _Diemtichluy;
		
		private EntitySet<VE> _VEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnNgaysinhChanging(System.DateTime value);
    partial void OnNgaysinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(int value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(int value);
    partial void OnCMNDChanged();
    partial void OnDiemtichluyChanging(int value);
    partial void OnDiemtichluyChanged();
    #endregion
		
		public Khach_Hang()
		{
			this._VEs = new EntitySet<VE>(new Action<VE>(this.attach_VEs), new Action<VE>(this.detach_VEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int NOT NULL")]
		public int SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int NOT NULL")]
		public int CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diemtichluy", DbType="Int NOT NULL")]
		public int Diemtichluy
		{
			get
			{
				return this._Diemtichluy;
			}
			set
			{
				if ((this._Diemtichluy != value))
				{
					this.OnDiemtichluyChanging(value);
					this.SendPropertyChanging();
					this._Diemtichluy = value;
					this.SendPropertyChanged("Diemtichluy");
					this.OnDiemtichluyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_Hang_VE", Storage="_VEs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<VE> VEs
		{
			get
			{
				return this._VEs;
			}
			set
			{
				this._VEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.Khach_Hang = this;
		}
		
		private void detach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.Khach_Hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Lich Chieu]")]
	public partial class Lich_Chieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLC;
		
		private System.DateTime _Ngaychieu;
		
		private string _Giochieu;
		
		private string _Trangthai;
		
		private EntitySet<VE> _VEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLCChanging(string value);
    partial void OnMaLCChanged();
    partial void OnNgaychieuChanging(System.DateTime value);
    partial void OnNgaychieuChanged();
    partial void OnGiochieuChanging(string value);
    partial void OnGiochieuChanged();
    partial void OnTrangthaiChanging(string value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public Lich_Chieu()
		{
			this._VEs = new EntitySet<VE>(new Action<VE>(this.attach_VEs), new Action<VE>(this.detach_VEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLC
		{
			get
			{
				return this._MaLC;
			}
			set
			{
				if ((this._MaLC != value))
				{
					this.OnMaLCChanging(value);
					this.SendPropertyChanging();
					this._MaLC = value;
					this.SendPropertyChanged("MaLC");
					this.OnMaLCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaychieu", DbType="DateTime NOT NULL")]
		public System.DateTime Ngaychieu
		{
			get
			{
				return this._Ngaychieu;
			}
			set
			{
				if ((this._Ngaychieu != value))
				{
					this.OnNgaychieuChanging(value);
					this.SendPropertyChanging();
					this._Ngaychieu = value;
					this.SendPropertyChanged("Ngaychieu");
					this.OnNgaychieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giochieu", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Giochieu
		{
			get
			{
				return this._Giochieu;
			}
			set
			{
				if ((this._Giochieu != value))
				{
					this.OnGiochieuChanging(value);
					this.SendPropertyChanging();
					this._Giochieu = value;
					this.SendPropertyChanged("Giochieu");
					this.OnGiochieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lich_Chieu_VE", Storage="_VEs", ThisKey="MaLC", OtherKey="MaLC")]
		public EntitySet<VE> VEs
		{
			get
			{
				return this._VEs;
			}
			set
			{
				this._VEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.Lich_Chieu = this;
		}
		
		private void detach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.Lich_Chieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phim")]
	public partial class Phim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Maphim;
		
		private string _Tenphim;
		
		private string _Mota;
		
		private string _Thoiluong;
		
		private System.DateTime _Ngaykhoichieu;
		
		private string _Daodien;
		
		private int _Namsx;
		
		private string _Matheloai;
		
		private string _Theloai;
		
		private string _Apphich;
		
		private EntitySet<VE> _VEs;
		
		private EntityRef<The_Loai> _The_Loai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphimChanging(int value);
    partial void OnMaphimChanged();
    partial void OnTenphimChanging(string value);
    partial void OnTenphimChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnThoiluongChanging(string value);
    partial void OnThoiluongChanged();
    partial void OnNgaykhoichieuChanging(System.DateTime value);
    partial void OnNgaykhoichieuChanged();
    partial void OnDaodienChanging(string value);
    partial void OnDaodienChanged();
    partial void OnNamsxChanging(int value);
    partial void OnNamsxChanged();
    partial void OnMatheloaiChanging(string value);
    partial void OnMatheloaiChanged();
    partial void OnTheloaiChanging(string value);
    partial void OnTheloaiChanged();
    partial void OnApphichChanging(string value);
    partial void OnApphichChanged();
    #endregion
		
		public Phim()
		{
			this._VEs = new EntitySet<VE>(new Action<VE>(this.attach_VEs), new Action<VE>(this.detach_VEs));
			this._The_Loai = default(EntityRef<The_Loai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphim", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Maphim
		{
			get
			{
				return this._Maphim;
			}
			set
			{
				if ((this._Maphim != value))
				{
					this.OnMaphimChanging(value);
					this.SendPropertyChanging();
					this._Maphim = value;
					this.SendPropertyChanged("Maphim");
					this.OnMaphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenphim", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tenphim
		{
			get
			{
				return this._Tenphim;
			}
			set
			{
				if ((this._Tenphim != value))
				{
					this.OnTenphimChanging(value);
					this.SendPropertyChanging();
					this._Tenphim = value;
					this.SendPropertyChanged("Tenphim");
					this.OnTenphimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoiluong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Thoiluong
		{
			get
			{
				return this._Thoiluong;
			}
			set
			{
				if ((this._Thoiluong != value))
				{
					this.OnThoiluongChanging(value);
					this.SendPropertyChanging();
					this._Thoiluong = value;
					this.SendPropertyChanged("Thoiluong");
					this.OnThoiluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaykhoichieu", DbType="DateTime NOT NULL")]
		public System.DateTime Ngaykhoichieu
		{
			get
			{
				return this._Ngaykhoichieu;
			}
			set
			{
				if ((this._Ngaykhoichieu != value))
				{
					this.OnNgaykhoichieuChanging(value);
					this.SendPropertyChanging();
					this._Ngaykhoichieu = value;
					this.SendPropertyChanged("Ngaykhoichieu");
					this.OnNgaykhoichieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daodien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Daodien
		{
			get
			{
				return this._Daodien;
			}
			set
			{
				if ((this._Daodien != value))
				{
					this.OnDaodienChanging(value);
					this.SendPropertyChanging();
					this._Daodien = value;
					this.SendPropertyChanged("Daodien");
					this.OnDaodienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namsx", DbType="Int NOT NULL")]
		public int Namsx
		{
			get
			{
				return this._Namsx;
			}
			set
			{
				if ((this._Namsx != value))
				{
					this.OnNamsxChanging(value);
					this.SendPropertyChanging();
					this._Namsx = value;
					this.SendPropertyChanged("Namsx");
					this.OnNamsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matheloai", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Matheloai
		{
			get
			{
				return this._Matheloai;
			}
			set
			{
				if ((this._Matheloai != value))
				{
					if (this._The_Loai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatheloaiChanging(value);
					this.SendPropertyChanging();
					this._Matheloai = value;
					this.SendPropertyChanged("Matheloai");
					this.OnMatheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Theloai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Theloai
		{
			get
			{
				return this._Theloai;
			}
			set
			{
				if ((this._Theloai != value))
				{
					this.OnTheloaiChanging(value);
					this.SendPropertyChanging();
					this._Theloai = value;
					this.SendPropertyChanged("Theloai");
					this.OnTheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apphich", DbType="NVarChar(50)")]
		public string Apphich
		{
			get
			{
				return this._Apphich;
			}
			set
			{
				if ((this._Apphich != value))
				{
					this.OnApphichChanging(value);
					this.SendPropertyChanging();
					this._Apphich = value;
					this.SendPropertyChanged("Apphich");
					this.OnApphichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_VE", Storage="_VEs", ThisKey="Maphim", OtherKey="Maphim")]
		public EntitySet<VE> VEs
		{
			get
			{
				return this._VEs;
			}
			set
			{
				this._VEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="The_Loai_Phim", Storage="_The_Loai", ThisKey="Matheloai", OtherKey="Matheloai", IsForeignKey=true)]
		public The_Loai The_Loai
		{
			get
			{
				return this._The_Loai.Entity;
			}
			set
			{
				The_Loai previousValue = this._The_Loai.Entity;
				if (((previousValue != value) 
							|| (this._The_Loai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._The_Loai.Entity = null;
						previousValue.Phims.Remove(this);
					}
					this._The_Loai.Entity = value;
					if ((value != null))
					{
						value.Phims.Add(this);
						this._Matheloai = value.Matheloai;
					}
					else
					{
						this._Matheloai = default(string);
					}
					this.SendPropertyChanged("The_Loai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_VEs(VE entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Phong Chieu]")]
	public partial class Phong_Chieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Maphong;
		
		private string _Marap;
		
		private int _Phongso;
		
		private int _Sochongoi;
		
		private string _Tinhtrang;
		
		private string _LoaiMH;
		
		private string _LoaiDD;
		
		private EntitySet<Ghe> _Ghes;
		
		private EntityRef<Rap_phim> _Rap_phim;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaphongChanging(string value);
    partial void OnMaphongChanged();
    partial void OnMarapChanging(string value);
    partial void OnMarapChanged();
    partial void OnPhongsoChanging(int value);
    partial void OnPhongsoChanged();
    partial void OnSochongoiChanging(int value);
    partial void OnSochongoiChanged();
    partial void OnTinhtrangChanging(string value);
    partial void OnTinhtrangChanged();
    partial void OnLoaiMHChanging(string value);
    partial void OnLoaiMHChanged();
    partial void OnLoaiDDChanging(string value);
    partial void OnLoaiDDChanged();
    #endregion
		
		public Phong_Chieu()
		{
			this._Ghes = new EntitySet<Ghe>(new Action<Ghe>(this.attach_Ghes), new Action<Ghe>(this.detach_Ghes));
			this._Rap_phim = default(EntityRef<Rap_phim>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maphong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Maphong
		{
			get
			{
				return this._Maphong;
			}
			set
			{
				if ((this._Maphong != value))
				{
					this.OnMaphongChanging(value);
					this.SendPropertyChanging();
					this._Maphong = value;
					this.SendPropertyChanged("Maphong");
					this.OnMaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marap", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Marap
		{
			get
			{
				return this._Marap;
			}
			set
			{
				if ((this._Marap != value))
				{
					if (this._Rap_phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMarapChanging(value);
					this.SendPropertyChanging();
					this._Marap = value;
					this.SendPropertyChanged("Marap");
					this.OnMarapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phongso", DbType="Int NOT NULL")]
		public int Phongso
		{
			get
			{
				return this._Phongso;
			}
			set
			{
				if ((this._Phongso != value))
				{
					this.OnPhongsoChanging(value);
					this.SendPropertyChanging();
					this._Phongso = value;
					this.SendPropertyChanged("Phongso");
					this.OnPhongsoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sochongoi", DbType="Int NOT NULL")]
		public int Sochongoi
		{
			get
			{
				return this._Sochongoi;
			}
			set
			{
				if ((this._Sochongoi != value))
				{
					this.OnSochongoiChanging(value);
					this.SendPropertyChanging();
					this._Sochongoi = value;
					this.SendPropertyChanged("Sochongoi");
					this.OnSochongoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiMH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiMH
		{
			get
			{
				return this._LoaiMH;
			}
			set
			{
				if ((this._LoaiMH != value))
				{
					this.OnLoaiMHChanging(value);
					this.SendPropertyChanging();
					this._LoaiMH = value;
					this.SendPropertyChanged("LoaiMH");
					this.OnLoaiMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiDD
		{
			get
			{
				return this._LoaiDD;
			}
			set
			{
				if ((this._LoaiDD != value))
				{
					this.OnLoaiDDChanging(value);
					this.SendPropertyChanging();
					this._LoaiDD = value;
					this.SendPropertyChanged("LoaiDD");
					this.OnLoaiDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_Chieu_Ghe", Storage="_Ghes", ThisKey="Maphong", OtherKey="Maphong")]
		public EntitySet<Ghe> Ghes
		{
			get
			{
				return this._Ghes;
			}
			set
			{
				this._Ghes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rap_phim_Phong_Chieu", Storage="_Rap_phim", ThisKey="Marap", OtherKey="Marap", IsForeignKey=true)]
		public Rap_phim Rap_phim
		{
			get
			{
				return this._Rap_phim.Entity;
			}
			set
			{
				Rap_phim previousValue = this._Rap_phim.Entity;
				if (((previousValue != value) 
							|| (this._Rap_phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rap_phim.Entity = null;
						previousValue.Phong_Chieus.Remove(this);
					}
					this._Rap_phim.Entity = value;
					if ((value != null))
					{
						value.Phong_Chieus.Add(this);
						this._Marap = value.Marap;
					}
					else
					{
						this._Marap = default(string);
					}
					this.SendPropertyChanged("Rap_phim");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.Phong_Chieu = this;
		}
		
		private void detach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.Phong_Chieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Rap phim]")]
	public partial class Rap_phim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Marap;
		
		private string _Tenrap;
		
		private string _Diachi;
		
		private EntitySet<Phong_Chieu> _Phong_Chieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMarapChanging(string value);
    partial void OnMarapChanged();
    partial void OnTenrapChanging(string value);
    partial void OnTenrapChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    #endregion
		
		public Rap_phim()
		{
			this._Phong_Chieus = new EntitySet<Phong_Chieu>(new Action<Phong_Chieu>(this.attach_Phong_Chieus), new Action<Phong_Chieu>(this.detach_Phong_Chieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marap", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Marap
		{
			get
			{
				return this._Marap;
			}
			set
			{
				if ((this._Marap != value))
				{
					this.OnMarapChanging(value);
					this.SendPropertyChanging();
					this._Marap = value;
					this.SendPropertyChanged("Marap");
					this.OnMarapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenrap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tenrap
		{
			get
			{
				return this._Tenrap;
			}
			set
			{
				if ((this._Tenrap != value))
				{
					this.OnTenrapChanging(value);
					this.SendPropertyChanging();
					this._Tenrap = value;
					this.SendPropertyChanged("Tenrap");
					this.OnTenrapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rap_phim_Phong_Chieu", Storage="_Phong_Chieus", ThisKey="Marap", OtherKey="Marap")]
		public EntitySet<Phong_Chieu> Phong_Chieus
		{
			get
			{
				return this._Phong_Chieus;
			}
			set
			{
				this._Phong_Chieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phong_Chieus(Phong_Chieu entity)
		{
			this.SendPropertyChanging();
			entity.Rap_phim = this;
		}
		
		private void detach_Phong_Chieus(Phong_Chieu entity)
		{
			this.SendPropertyChanging();
			entity.Rap_phim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[The Loai]")]
	public partial class The_Loai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Matheloai;
		
		private string _Tentheloai;
		
		private EntitySet<Phim> _Phims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatheloaiChanging(string value);
    partial void OnMatheloaiChanged();
    partial void OnTentheloaiChanging(string value);
    partial void OnTentheloaiChanged();
    #endregion
		
		public The_Loai()
		{
			this._Phims = new EntitySet<Phim>(new Action<Phim>(this.attach_Phims), new Action<Phim>(this.detach_Phims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matheloai", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Matheloai
		{
			get
			{
				return this._Matheloai;
			}
			set
			{
				if ((this._Matheloai != value))
				{
					this.OnMatheloaiChanging(value);
					this.SendPropertyChanging();
					this._Matheloai = value;
					this.SendPropertyChanged("Matheloai");
					this.OnMatheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentheloai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tentheloai
		{
			get
			{
				return this._Tentheloai;
			}
			set
			{
				if ((this._Tentheloai != value))
				{
					this.OnTentheloaiChanging(value);
					this.SendPropertyChanging();
					this._Tentheloai = value;
					this.SendPropertyChanged("Tentheloai");
					this.OnTentheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="The_Loai_Phim", Storage="_Phims", ThisKey="Matheloai", OtherKey="Matheloai")]
		public EntitySet<Phim> Phims
		{
			get
			{
				return this._Phims;
			}
			set
			{
				this._Phims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phims(Phim entity)
		{
			this.SendPropertyChanging();
			entity.The_Loai = this;
		}
		
		private void detach_Phims(Phim entity)
		{
			this.SendPropertyChanging();
			entity.The_Loai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accout")]
	public partial class Accout : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _Matkhau;
		
		private int _LoaiTK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnLoaiTKChanging(int value);
    partial void OnLoaiTKChanged();
    #endregion
		
		public Accout()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{ 
			[DataType(DataType.Password)]
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTK", DbType="Int NOT NULL")]
		public int LoaiTK
		{
			get
			{
				return this._LoaiTK;
			}
			set
			{
				if ((this._LoaiTK != value))
				{
					this.OnLoaiTKChanging(value);
					this.SendPropertyChanging();
					this._LoaiTK = value;
					this.SendPropertyChanged("LoaiTK");
					this.OnLoaiTKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
